project:
  type: website
  output-dir: docs
  resources: 
    - earcons/*.mp3

website:
  title: "Audiofunctions+"
  navbar:
    left:
      - text: "Shortcuts"
        href: shortcuts.md
      - text: "Earcons"
        href: earcons.md
    # right:
    #   - about.qmd
  
  sidebar: 
    contents:
      - text: "Shortcuts"
        href: shortcuts.qmd
 
  page-footer: 
    left: Produced with [Quarto](https://quarto.org/)
    right: "Maintained by the SONAIRGRAPH dev team"

format:
  html:
    theme: 
         - cosmo
         - custom.scss
    css: styles.css
    toc: false
    logo: "logo.png"
    sidebar: false
    lang: en



